baseURL = "https://fillmem.com"
title = "Fill the memory"
copyright = ""

theme = "minimo"

disqusShortname = ""
googleAnalytics = "UA-105858064-1"
Paginate = 5

preserveTaxonomyNames = true

pygmentsCodeFences = false
pygmentsCodeFencesGuessSyntax = false
pygmentsStyle = "emacs"
pygmentsUseClasses = false

[params]
  description = "To move forward and to avoid losing time on the same things"
  dateFormat = "2006, Jan 2"
  copyrightOwner = "Guillaume Sempe"
  copyrightStartYear = "2017"
  favicon = "favicon.ico"
  hideEntryNavigation = false
  customCSS = ["css/prism.css", "css/custom.css"]
  customJS = ["js/prism.js", "js/custom.js"]
  hideSocialMenu = false
  showReadTime = true

[params.seo]
  # Title Separator: - – — · • * ⋆ | ~ « » < >
  titleSeparator = "•"

[params.opengraph]
  [params.opengraph.facebook]
    admins = ""
    appid = ""

[taxonomies]
  category = "categories"
  tag = "tags"

[social]
  facebook = ""

[author]
  name = "gsempe"

[author.social]
  codepen = ""
  email = "guillaume.sempe@gmail.com"
  facebook = "gsempe"
  github = "gsempe"
  instagram = "gsempe"
  twitter = "tx"
  linkedin = "gsempe"

[permalinks]
  page = "/:slug/"

[[menu.main]]
  name = "Blog"
  weight = -70
  identifier = "fillmem"
  url = "https://fillmem.com"

# Language Configuration
defaultContentLanguage = "en"

[languages]
  # edit this block for your own language
  [languages.en]
    lang = "en"
    languageName = "English"
    weight = 1
